/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.sun.jdi.connect.spi.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.root.Person;
import static ui.RegisterFrame.registerFrame;
import com.db4o.Db4oEmbedded;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.backend.Db4oUtils;
import model.backend.OperatingSystem;
import model.root.ApprovalEmployee;
import model.root.ApprovalOfficer;
import model.root.Assembler;
import model.root.Customer;
import model.root.IdChecker;
import model.root.ManufacturerAdmin;
import model.root.Person.UserRole;
import static model.root.Person.UserRole.CUSTOMER;
import model.root.RegionalManager;
import model.root.RegulatorAdmin;
import model.root.StoreManager;
import model.root.Tester;
import model.root.UserTest;
        
 public class LoginFrame extends javax.swing.JFrame {
    
    public static JFrame loginFrame;
    private OperatingSystem operatingSystem;
    private Db4oUtils dB4OUtility;
    
    public LoginFrame() {
    }

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame(Db4oUtils db ,OperatingSystem os) {
        initComponents();
        System.out.println(db+"\t"+os);
        this.operatingSystem = os;
        this.dB4OUtility = db;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginUsernameText = new javax.swing.JTextField();
        loginPasswordText = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        loginButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Login Page");

        lblTitle1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Weapon Management System");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        loginUsernameText.setBackground(new java.awt.Color(32, 33, 35));
        loginUsernameText.setForeground(new java.awt.Color(255, 255, 255));
        loginUsernameText.setBorder(null);

        loginPasswordText.setBackground(new java.awt.Color(32, 33, 35));
        loginPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordText.setBorder(null);
        loginPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordTextActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        loginButton.setBackground(new java.awt.Color(126, 87, 194));
        loginButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        goBackButton.setBackground(new java.awt.Color(126, 87, 194));
        goBackButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setText("Go Back <<<<<");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(loginUsernameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(loginPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goBackButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordTextActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        MainFrame.mainFrame.setVisible(true);
        loginFrame.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:   
        String user = loginUsernameText.getText().trim();
        String pass = new String(loginPasswordText.getPassword());
        
        List<Person> personsList = operatingSystem.getPersonDirectory();
        
        Person person = personsList.stream()
                        .filter(p -> p.getUsername().equals(user) && p.getPassword().equals(pass))
                        .findFirst()
                        .orElse(null);
        if(person == null){
            JOptionPane.showMessageDialog(null, "Username or password is incorrect. Please check again");
            return;
        }
        
        
        switch(UserRole.valueOf(person.getRole())){
            
            case CUSTOMER: Customer cust = (Customer) person;
                           if(cust.approvalStatus==false){
                               JOptionPane.showMessageDialog(null, "Account Yet to be Verified");
                               break;
                           }
        
                           CustomerFrame.customerFrame = new CustomerFrame(dB4OUtility, operatingSystem,(Customer) person);
                           CustomerFrame.customerFrame.setVisible(true);
                           loginFrame.setVisible(false);
                           break;
            case REGIONAL_MANAGER: RegionalManagerFrame.regFrame = new RegionalManagerFrame(dB4OUtility, operatingSystem,(RegionalManager) person);
                           RegionalManagerFrame.regFrame.setVisible(true);
                           loginFrame.setVisible(false);
                           break;
            case TESTER: TesterFrame.testerFrame = new TesterFrame(dB4OUtility,operatingSystem, (Tester) person);
                         TesterFrame.testerFrame.setVisible(true);
                         break;
                         
            case APPROVAL_OFFICER: ApprovalManagerFrame.apprFrame= new ApprovalManagerFrame(dB4OUtility,operatingSystem, (ApprovalOfficer) person);
                                   ApprovalManagerFrame.apprFrame.setVisible(true);
                                   break;

            case REGULATOR_SYSADMIN: RegulatorAdminFrame.regAdminFrame = new RegulatorAdminFrame(dB4OUtility, operatingSystem,(RegulatorAdmin) person);
                           RegulatorAdminFrame.regAdminFrame.setVisible(true);
                           loginFrame.setVisible(false);
                           break;
            case MANUFACTURER_SYSADMIN: ManufacturerAdminFrame.manuAdminFrame = new ManufacturerAdminFrame(dB4OUtility, operatingSystem,(ManufacturerAdmin) person);
                           ManufacturerAdminFrame.manuAdminFrame .setVisible(true);
                           loginFrame.setVisible(false);
                           break;            
                           
            case ACCOUNT_VERIFYER: IdCheckerJFrame.idcheckFrame = new IdCheckerJFrame(dB4OUtility, operatingSystem,(IdChecker) person);
                           IdCheckerJFrame.idcheckFrame.setVisible(true);
                           loginFrame.setVisible(false);
                                       
                           break;
            case ASSEMBLER: AssemblerFrame.assFrame = new AssemblerFrame(dB4OUtility, operatingSystem, (Assembler) person);
                           AssemblerFrame.assFrame.setVisible(true);
                           loginFrame.setVisible(false);
                           break;
            
            case STORE_MANAGER: StoreManagerJFrame.storeFrame = new StoreManagerJFrame(dB4OUtility, operatingSystem, (StoreManager) person);
                                StoreManagerJFrame.storeFrame.setVisible(true);
                                loginFrame.setVisible(false);
                                break;
                                
            case APPROVAL_EMPLOYEE: ApprovalEmployeeFrame.apprEmpFrame = new ApprovalEmployeeFrame(dB4OUtility, operatingSystem, (ApprovalEmployee) person);
                                ApprovalEmployeeFrame.apprEmpFrame.setVisible(true);
                                loginFrame.setVisible(false);
                                break;
                                
            default: JOptionPane.showMessageDialog(null, "Something went wrong");
                           
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments/
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(loginFrame == null){
                    loginFrame = new LoginFrame();
                }
                
                loginFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField loginPasswordText;
    private javax.swing.JTextField loginUsernameText;
    // End of variables declaration//GEN-END:variables
}
