/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pho3nix28
 */
public class RegisterFrame extends javax.swing.JFrame {
    
    public static JFrame registerFrame;
    String gender;

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        registerFrameNameButton = new javax.swing.JTextField();
        registerFrameSsnButton = new javax.swing.JTextField();
        registerFrameMaleButton = new javax.swing.JRadioButton();
        registerFrameFemaleButton = new javax.swing.JRadioButton();
        registerFrameOtherButton = new javax.swing.JRadioButton();
        registerFrameBirthButton = new com.toedter.calendar.JDateChooser();
        registerFramePhoneButton = new javax.swing.JTextField();
        registerFrameEmailButton = new javax.swing.JTextField();
        registerFrameAddressButton = new javax.swing.JTextField();
        registerFrameUpdateButton = new javax.swing.JTextField();
        registerFramePasswordButton = new javax.swing.JPasswordField();
        registerFrameCreateAccountButton = new javax.swing.JButton();
        registerFrameGoBackButton = new javax.swing.JButton();
        registerFrameImportButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date of Birth:");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SSN:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username:");

        lblTitle1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Register Page");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Weapon Management System");

        registerFrameNameButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerFrameNameButtonFocusLost(evt);
            }
        });
        registerFrameNameButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerFrameNameButtonKeyPressed(evt);
            }
        });

        registerFrameSsnButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerFrameSsnButtonKeyPressed(evt);
            }
        });

        registerFrameMaleButton.setForeground(new java.awt.Color(255, 255, 255));
        registerFrameMaleButton.setText("Male");
        registerFrameMaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFrameMaleButtonActionPerformed(evt);
            }
        });

        registerFrameFemaleButton.setForeground(new java.awt.Color(255, 255, 255));
        registerFrameFemaleButton.setText("Female");
        registerFrameFemaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFrameFemaleButtonActionPerformed(evt);
            }
        });

        registerFrameOtherButton.setForeground(new java.awt.Color(255, 255, 255));
        registerFrameOtherButton.setText("Other");
        registerFrameOtherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFrameOtherButtonActionPerformed(evt);
            }
        });

        registerFramePhoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFramePhoneButtonActionPerformed(evt);
            }
        });
        registerFramePhoneButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerFramePhoneButtonKeyPressed(evt);
            }
        });

        registerFrameEmailButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerFrameEmailButtonFocusLost(evt);
            }
        });

        registerFramePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFramePasswordButtonActionPerformed(evt);
            }
        });

        registerFrameCreateAccountButton.setBackground(new java.awt.Color(126, 87, 194));
        registerFrameCreateAccountButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        registerFrameCreateAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        registerFrameCreateAccountButton.setText("Create Account");

        registerFrameGoBackButton.setBackground(new java.awt.Color(126, 87, 194));
        registerFrameGoBackButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        registerFrameGoBackButton.setForeground(new java.awt.Color(255, 255, 255));
        registerFrameGoBackButton.setText("Go Back <<<<<");
        registerFrameGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFrameGoBackButtonActionPerformed(evt);
            }
        });

        registerFrameImportButton.setBackground(new java.awt.Color(204, 204, 204));
        registerFrameImportButton.setFont(new java.awt.Font("Copperplate", 0, 13)); // NOI18N
        registerFrameImportButton.setForeground(new java.awt.Color(0, 0, 0));
        registerFrameImportButton.setText("Import");
        registerFrameImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerFrameImportButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Proof:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerFrameGoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerFrameCreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(registerFrameMaleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerFrameFemaleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerFrameOtherButton))
                            .addComponent(registerFrameBirthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registerFramePasswordButton)
                            .addComponent(registerFrameUpdateButton)
                            .addComponent(registerFrameAddressButton)
                            .addComponent(registerFrameEmailButton)
                            .addComponent(registerFramePhoneButton)
                            .addComponent(registerFrameSsnButton)
                            .addComponent(registerFrameNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerFrameImportButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(registerFrameNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(registerFrameSsnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(registerFrameMaleButton)
                    .addComponent(registerFrameFemaleButton)
                    .addComponent(registerFrameOtherButton))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(registerFrameBirthButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(registerFramePhoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(registerFrameEmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(registerFrameAddressButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(registerFrameUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(registerFramePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(registerFrameImportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(registerFrameCreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerFrameGoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerFrameMaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFrameMaleButtonActionPerformed
        // TODO add your handling code here:
         if(registerFrameMaleButton.isSelected()){
            gender = "Male";
            registerFrameFemaleButton.setSelected(false);
            registerFrameOtherButton.setSelected(false);
        }
    }//GEN-LAST:event_registerFrameMaleButtonActionPerformed

    private void registerFrameGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFrameGoBackButtonActionPerformed
        // TODO add your handling code here:
        MainFrame.mainFrame.setVisible(true);
        registerFrame.setVisible(false);
    }//GEN-LAST:event_registerFrameGoBackButtonActionPerformed

    private void registerFrameFemaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFrameFemaleButtonActionPerformed
        // TODO add your handling code here:
        if(registerFrameFemaleButton.isSelected()){
            gender = "Male";
            registerFrameMaleButton.setSelected(false);
            registerFrameOtherButton.setSelected(false);
        }
    }//GEN-LAST:event_registerFrameFemaleButtonActionPerformed

    private void registerFramePhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFramePhoneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerFramePhoneButtonActionPerformed

    private void registerFramePhoneButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerFramePhoneButtonKeyPressed
        // TODO add your handling code here:
        
           String phoneNumber = registerFramePhoneButton.getText();
        int lengthOfNumber = phoneNumber.length();
        char checkChar = evt.getKeyChar();
        if (checkChar >= '0' && checkChar <= '9') {
            if (lengthOfNumber < 10) {
                registerFramePhoneButton.setEditable(true);
            } else {
                registerFramePhoneButton.setEditable(false);
                JOptionPane.showMessageDialog(this, "Cannot add more than 10 Numbers!");
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                registerFramePhoneButton.setEditable(true);
            } else {
                registerFramePhoneButton.setEditable(false);
            }
        }
    }//GEN-LAST:event_registerFramePhoneButtonKeyPressed

    private void registerFrameNameButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerFrameNameButtonKeyPressed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_registerFrameNameButtonKeyPressed

    private void registerFrameNameButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerFrameNameButtonFocusLost
        // TODO add your handling code here:
        
          Pattern p = Pattern.compile("[^A-Za-z ]");
        Matcher m = p.matcher(registerFrameNameButton.getText());
        // boolean b = m.matches();
        boolean b = m.find();
        if (b){
            JOptionPane.showMessageDialog(null,"Special Characters are not allowed.");
            registerFrameNameButton.setText("");
        }
    }//GEN-LAST:event_registerFrameNameButtonFocusLost

    private void registerFrameEmailButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerFrameEmailButtonFocusLost
        // TODO add your handling code here:
        
        String emailFormat ="^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+(?:\\."+ "[a-zA-Z0-9_!#$%&'*+/=?`{|}~^-]+)*@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"; 
        Pattern employeeEmail = Pattern.compile(emailFormat) ;
        Matcher employeeEmailMatch = employeeEmail.matcher(registerFrameEmailButton.getText());
        
        if (!employeeEmailMatch.matches()){
            JOptionPane.showMessageDialog(null,"Invalid Email!");
            registerFrameEmailButton.setText("");
        } 
    }//GEN-LAST:event_registerFrameEmailButtonFocusLost

    private void registerFrameSsnButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerFrameSsnButtonKeyPressed
        // TODO add your handling code here:
        
         String ssn = registerFrameSsnButton.getText();
        int lengthOfNumber = ssn.length();
        char checkChar = evt.getKeyChar();
        if (checkChar >= '0' && checkChar <= '9') {
            if (lengthOfNumber < 9) {
                registerFrameSsnButton.setEditable(true);
            } else {
                registerFrameSsnButton.setEditable(false);
                JOptionPane.showMessageDialog(this, "Cannot add more than 10 Numbers!");
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                registerFrameSsnButton.setEditable(true);
            } else {
                registerFrameSsnButton.setEditable(false);
            }
        }
        
        
        
    }//GEN-LAST:event_registerFrameSsnButtonKeyPressed

    private void registerFrameOtherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFrameOtherButtonActionPerformed
        // TODO add your handling code here:
        if(registerFrameOtherButton.isSelected()){
            gender = "Male";
            registerFrameMaleButton.setSelected(false);
            registerFrameFemaleButton.setSelected(false);
        }
    }//GEN-LAST:event_registerFrameOtherButtonActionPerformed

    private void registerFramePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFramePasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerFramePasswordButtonActionPerformed

    private void registerFrameImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFrameImportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerFrameImportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(registerFrame == null){
                    registerFrame = new RegisterFrame();
                }
                
                registerFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTextField registerFrameAddressButton;
    private com.toedter.calendar.JDateChooser registerFrameBirthButton;
    private javax.swing.JButton registerFrameCreateAccountButton;
    private javax.swing.JTextField registerFrameEmailButton;
    private javax.swing.JRadioButton registerFrameFemaleButton;
    private javax.swing.JButton registerFrameGoBackButton;
    private javax.swing.JButton registerFrameImportButton;
    private javax.swing.JRadioButton registerFrameMaleButton;
    private javax.swing.JTextField registerFrameNameButton;
    private javax.swing.JRadioButton registerFrameOtherButton;
    private javax.swing.JPasswordField registerFramePasswordButton;
    private javax.swing.JTextField registerFramePhoneButton;
    private javax.swing.JTextField registerFrameSsnButton;
    private javax.swing.JTextField registerFrameUpdateButton;
    // End of variables declaration//GEN-END:variables
}
