/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author pho3nix28
 */
public class ShippingManagerOrders extends javax.swing.JPanel {

    /**
     * Creates new form ShippingManagerOrders
     */
    public ShippingManagerOrders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shippingManOrderTable = new javax.swing.JTable();
        shippingManViewOrderButton = new javax.swing.JButton();
        shippingManUpdateButton = new javax.swing.JButton();
        shippingManDeleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(32, 33, 35));
        setPreferredSize(new java.awt.Dimension(695, 800));

        lblTitle1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Supplier-Dealer Order Management");

        shippingManOrderTable.setBackground(new java.awt.Color(255, 255, 255));
        shippingManOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(shippingManOrderTable);

        shippingManViewOrderButton.setBackground(new java.awt.Color(126, 87, 194));
        shippingManViewOrderButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        shippingManViewOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        shippingManViewOrderButton.setText("View Order");

        shippingManUpdateButton.setBackground(new java.awt.Color(126, 87, 194));
        shippingManUpdateButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        shippingManUpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        shippingManUpdateButton.setText("Update");

        shippingManDeleteButton.setBackground(new java.awt.Color(126, 87, 194));
        shippingManDeleteButton.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        shippingManDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        shippingManDeleteButton.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shippingManViewOrderButton)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(shippingManUpdateButton)
                .addGap(31, 31, 31)
                .addComponent(shippingManDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shippingManViewOrderButton)
                .addGap(235, 235, 235)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shippingManUpdateButton)
                    .addComponent(shippingManDeleteButton))
                .addContainerGap(323, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JButton shippingManDeleteButton;
    private javax.swing.JTable shippingManOrderTable;
    private javax.swing.JButton shippingManUpdateButton;
    private javax.swing.JButton shippingManViewOrderButton;
    // End of variables declaration//GEN-END:variables
}
